name: '🐛 Bug report'
description: Report a reproducible bug or regression
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue :pray:.

        Before submitting a new bug/issue, please check the links below to see if there is a solution or question posted there already:
        - material-solid-table's [Discussions tab](https://github.com/material/material-solid-table/discussions)
        - material-solid-table's [Open Issues](https://github.com/KevinVandy/material-solid-table/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
        - material-solid-table's [Closed Issues](https://github.com/KevinVandy/material-solid-table/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)

        The more information you fill in, the better the community can help you.

  - type: input
    id: library-version
    attributes:
      label: material-solid-table version
      description: |
        - Please let us know the exact version of material-solid-table you were using when the issue occurred. If you are using an older version, check to see if your bug has already been solved in the latest version. 
        - The latest version is <img alt="" src="https://badgen.net/npm/v/material-solid-table" />
      placeholder: |
        e.g. v0.15.4
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug and the steps to reproduce it
      description: Provide a clear and concise description of the challenge you are running into, and the steps we should take to try to reproduce your bug.
    validations:
      required: true

  - type: textarea
    id: link
    attributes:
      label: Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets
      description: |
        Please add a link to a minimal reproduction. This can really speed up the diagnosis of the problem! A Code Sandbox is preferable, but simple code snippets are also acceptable here.
        Note:
          - Your bug may get fixed much faster if we can run your code and it doesn't have dependencies other than Solid and the SUID dependencies.
          - To create a shareable code example for web, you can use CodeSandbox (https://codesandbox.io/s/new).
          - Please make sure the example is complete and runnable without prior dependencies and free of unnecessary abstractions
          - Feel free to fork any of the official CodeSandbox examples to reproduce your issue: https://github.com/KevinVandy/material-solid-table/tree/main/material-solid-table-docs/examples
          - Please read these tips for providing a minimal example: https://stackoverflow.com/help/mcve.
      placeholder: |
        e.g. Code Sandbox, Stackblitz, or relevant code snippets.
    validations:
      required: true

  - type: textarea
    id: screenshots_or_videos
    attributes:
      label: Screenshots or Videos (Optional)
      description: |
        If applicable, add screenshots or a video to help explain your problem.
        For more information on the supported file image/file types and the file size limits, please refer
        to the following link: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files
      placeholder: |
        You can drag your video or image files inside of this editor ↓

  - type: dropdown
    attributes:
      options:
        - No, because I don't know how
        - No, because I don't have time to dig into it
        - Maybe, I'll investigate and start debugging
        - Yes, I think I know how to fix it and will discuss it in the comments of this issue
        - Yes, I am also opening a PR that solves the problem along side this issue
      label: Do you intend to try to help solve this bug with your own PR?
      description: |
        If you think you know the cause of the problem, the fastest way to get it fixed is to suggest a fix, or fix it yourself! It is ok if you cannot solve this yourself and are just wanting help.

  - type: checkboxes
    id: agrees-to-terms
    attributes:
      label: Terms
      description: By submitting this issue, you agree to follow our Code of Conduct and can verify that you have followed the requirements outlined above to the best of your ability.
      options:
        - label: I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.
          required: true
